name = "gitorum"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_REPO_OWNER = "yihui"
GITHUB_REPO_NAME = "yihui.org"
GITHUB_APP_ID = "2978964"
GITHUB_APP_INSTALLATION_ID = "113236407"
